version: '3.3'

services:
  postgres:
    image: postgres:13-alpine
    container_name: taco
    expose:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: taco
      POSTGRES_PASSWORD: taco

    volumes:
      - "taco-service:/var/lib/postgresql/data"
    networks:
      - service

networks:
  service:
volumes:
  taco-service: